name: create-landing-page
on:
  push:
    branches:
      - 'master'
      - 'cff_test'
    paths:
      - 'CITATION.cff'
  release:
    types: [published]

jobs:
  update-landing-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Update pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cffconvert==1.3.3
      - name: Create landing page based on trigger
        if: ${{ env.GITHUB_EVENT_NAME == push }}
        env:
          PAGE_TYPE: latest
        if: ${{ env.GITHUB_EVENT_NAME == release }}
        env:
          PAGE_TYPE: ${{ github.event.release.name }}
        run: python write_doi_landing_page.py ${{ env.PAGE_TYPE }}
