name: run-tests
on:
  push:
  pull_request:
    types: [opened, reopened, labeled]
  workflow_dispatch:

jobs:
  test:
    if: github.event.action != 'labeled' || github.event.label.name == 'run CI'
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
      - name: Update pip and install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests_and_analysis/ci_requirements.txt
          python -m pip install -r tests_and_analysis/tox_requirements.txt
          python -m pip install .[matplotlib,phonopy_reader]
      - name: SSH with tmate for debugging
        uses: mxschmitt/action-tmate@v3
