name: run-tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
      - name: Update pip and install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests_and_analysis/ci_requirements.txt
      - name: Run tests
        shell: bash -l {0}
        run: python -m tox
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: |
          startsWith(matrix.os, 'ubuntu') &&
          always()
        with:
          files: tests_and_analysis/test/reports/junit_report*.xml
      - name: Publish coverage
        uses: codecov/codecov-action@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: coverage.xml
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codacy/codacy-analysis-cli-action@4.0.0
        with:
          directory: $PWD/euphonic
