name: run-tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Update pip and install dependencies
        run: |
          python -m pip install --upgrade --user pip
          python -m pip install -r tests_and_analysis/jenkins_requirements.txt
      - name: Run tests
        run: python -m tox
      - uses: codecov/codecov-action@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          files: coverage.xml
