name: test-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The Euphonic release version to test e.g. 0.6.1'
        required: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v{{ github.event.inputs.version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
      - name: Update pip and install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests_and_analysis/ci_requirements.txt
      - name: Run tests
        shell: bash -l {0}
        env:
          EUPHONIC_VERSION: {{ github.event.inputs.version }}
        run: python -m tox -c release_tox.ini
      - name: Publish test results Linux
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: |
          startsWith(matrix.os, 'ubuntu') &&
          always()
        with:
          files: tests_and_analysis/test/reports/junit_report*.xml
      - name: Publish test results Mac/Windows
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: |
          (startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'windows')) &&
          always()
        with:
          files: tests_and_analysis/test/reports/junit_report*.xml
