name: test-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The Euphonic release version to test e.g. 0.6.1'
        required: true
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v0.6.1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
      - name: Update pip and install dependencies
        run: |
          python -m pip install --upgrade --user pip
          python -m pip install -r tests_and_analysis/jenkins_requirements.txt
      - name: Run tests
        env:
          EUPHONIC_VERSION: v0.6.1
        run: python -m tox -c release_tox.ini

